### PR TITLE
ngspice-analysis: added measuring current feature, closes #176

### LINKED ISSUE #176: support for measuring amperage
### Steps to reproduce
1. start Oregano
2. open [tryAmmeter.oregano](https://github.com/drahnr/oregano/files/1029800/tryAmmeter.oregano.txt)
3. run simulation
4. try to plot amperage

### Expected behaviour
ammeter button should be there

### Actual behaviour
there is nothing like an ammeter button

### Configuration
**Operating system**:
```
$ cat /etc/os-release |grep PRETTY_NAME
PRETTY_NAME="Ubuntu 16.10"
```

**Versions**
```
$ oregano --version
Oregano 0.84.3
 Website: https://ahoi.io/projects/oregano
 License: GPLv2/GPLv3
 Main Developer: Bernhard Schuster
$ ngspice --version
ngspice compiled from ngspice revision 26
Written originally by Berkeley University
Currently maintained by the NGSpice Project

Copyright (C) 1985-1996,  The Regents of the University of California
Copyright (C) 1999-2011,  The NGSpice Project
```

### PR DESCRIPTION
**Pull request by Michi1994**
What's new:

- current will be plotted by setting the checkbox of "Simulation Settings"->"Transient"->"Analyze All Currents And Potentials (only ngspice)"
- no limitation of number of nodes to analyze any more (it was limited to max 9)
- elimination of some memory leaks
- function `void parse_transient_analysis (OreganoNgSpice *ngspice, gchar *tmp)` has no memory leaks (checked with help of `valgrind --tool=massif`)
- increased third number of oregano version from `0.84.3` to `0.84.4`, because it's only a small feature
- making code a bit prettier (deprecation, unused variables, ...)

### CODE REVIEW

File: src/engines/ngspice-analysis.c [hunk 1]
```diff
@@ -195,229 +191,256 @@ void parse_dc_analysis (OreganoNgSpice *ngspice, gchar *tmp)
...
+		ret_val->unit = g_string_new("current");
+	else
+		ret_val->unit = g_string_new("unknown");
+
+	ret_val->data = g_array_sized_new(TRUE, TRUE, sizeof(gdouble), predicted_size);
+	ret_val->min = G_MAXDOUBLE;
+	ret_val->max = -G_MAXDOUBLE;
+
+	return ret_val;
+}
```
Comment (Michi1994) [inline src/engines/ngspice-analysis.c]: I fixed it in pull request #180.

File: src/engines/ngspice-analysis.c [hunk 2]
```diff
@@ -195,229 +191,256 @@ void parse_dc_analysis (OreganoNgSpice *ngspice, gchar *tmp)
...
 
-	NG_DEBUG ("TRANSIENT: result str\n>>>\n%s<<<\n", tmp);
+static void asdf(gpointer data) {
+	g_free(data);
+}
```
Comment (Michi1994) [inline src/engines/ngspice-analysis.c]: I fixed it in pull request #180.
